### ISSUE TITLE
Vanilla API get not found using the provided endpoint

### ISSUE THREAD

**Issue by gregroiusairlangga** [kasperisager/vanilla-api#61] opened 2015-08-31 05:34 UTC
Hi!

I am using Vanilla, version 2.2.12, and Vanilla API addon, version 0.4, and i use apache web server

The endpoint i get in API config is http://bkkbn.dojo-box.com/index.php?p=/api/

But i get not found everytime i try to acces, i try with the postman client collection that kasper provided, and still getting not found.

Someone have a lead what could be, or what i am doing wrong?

Thanks in advance

**Comment by kasperisager** [comment] 2015-08-31 08:25
Possible duplicate of #50.

**Comment by gregroiusairlangga** [comment] 2015-09-11 11:48
hello, sorry sir i still cannot open this API, i try to fix endpoint but
nothing change happen.. here is a screenshoot and url that i used. any help
will be appreciated

http://bkkbn.dojo-box.com/index.php?p=api/categories

thankyou

2015-08-31 15:25 GMT+07:00 Kasper Isager <notifications@github.com>:

**Comment by Wirty** [comment] 2015-09-14 09:29
if your server work without nginx, try to change your .htaccess
````
<IfModule mod_rewrite.c>
   RewriteEngine On
   RewriteBase /vanilla
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteRule ^(.*)$ index.php\?p=$1 [QSA,L]
</IfModule>
````

**Comment by kasperisager** [comment] 2016-01-24 14:17
Closing as an environment issue.

**Closed by kasperisager** 2016-01-24 14:17 UTC
