### ISSUE TITLE
404 not found on fresh installation

### ISSUE THREAD

**Issue by xDaizu** [kasperisager/vanilla-api#53] opened 2015-06-01 08:33 UTC
Today I updated Vanilla to the most recent master release, installed the current master branch api and it throws a 404 on every request to {{vanilla}}/api. 

Maybe something's changed in the Vanilla router?

**Comment by kasperisager** [comment] 2015-06-02 13:39
Possibly a duplicate of #28.

**Comment by xDaizu** [comment] 2015-06-02 14:06
Not a duplicate, Im accessing the same URLs (with al its /users and all its parameters) as before the Vanilla update, through php scripts, POSTman and browser ;)

**Comment by kasperisager** [comment] 2015-07-27 10:56
Closing this as an environment specific issue as I've not been able to replicate it at all.

**Closed by kasperisager** 2015-07-27 10:56 UTC
