### ISSUE TITLE
Installing API 0.4.0 for Vanilla forums

### ISSUE THREAD

**Issue by domagopolis** [kasperisager/vanilla-api#56] opened 2015-08-12 01:14 UTC
Yesterday I tried installing your plugin for vanilla forums so I can use a number of endpoints it has to offer. I got to the point of generating an endpoint url and secret but the url generated gives me a page not found error. http://localhost:8888/vanilla-forum/index.php?p=/api

**Comment by kasperisager** [comment] 2015-08-12 10:24
Duplicate of #28 and #50.

**Closed by kasperisager** 2015-08-12 10:24 UTC
